### ISSUE TITLE
question about the pretrain weights

### ISSUE THREAD

**Issue by Ming-er** [Audio-WestlakeU/ATST-SED#1]
Hi, thanks for your valuable works. I have a question about the pretrained ckpt: is it pretrained solely with self-supervised algorithms or further trained on AudioSet with supervised tagging tasks?

**Comment by SaoYear** [comment]
Hi, 

Thanks for the interest!

The pretrained ckpt is fine-tuned by the AudioSet. This step of AudioSet fine-tuning is helpful for the DESED fine-tuning. As the baseline system did in the DCASE 2023 task 4, it used BEATs iter3+ ckpt for the challenge.

**Comment by SaoYear** [comment]
I close this issue if there is no further question.
