### ISSUE TITLE
About change yaml path

### ISSUE THREAD

**Issue by Kiri0824** [Audio-WestlakeU/ATST-SED#10]
hey, i download all your website dataset:DESED dataset, Weakly labeled data: 44.1kHz, multi-channel, Strongly labeled REAL data: 44.1kHz, multi-channel, Development data: 16kHz, multi-channel, Extra strongly-labeled data. But i dont't know how to change stage1.yaml and stage2.yaml. Are there any other data sets that need to be downloaded? or its enough. if enough, could you tell me the details about how to change yaml path.😭 Thank you so much!!!

**Comment by SaoYear** [comment]
Hi Kiri,

1. The datasets provided in my personal site is NOT the full DCASE dataset. You should download some other datasets: 
-  strongly-labeled synthetic dataset (generated by Scaper according to the DCASE task 4 intro, 10000 audio clips); 
-  unsupervised  14412 audio clips;
-  If you want to use 2024 baseline dataset, download [MAESTRO](https://arxiv.org/pdf/2302.14572.pdf) dataset;

2. Once you downloaded this dataset, replace the following terms in yaml files:
- `weak_folder_44k`: weak real dataset path
- `weak_folder`: weak real dataset path + "_16k" postfix (the codes would automatically resample the wavform to 16k and save them to this path)
- Similarly from the weak folder, change `strong_folder` - strongly real dataset; `synth_folder` - strongly synthetic folder; `test_folder` - strongly real development set and so force;

I would recommend you to run the dcase 2023 baseline first, by which you could know how the data is organized. And then run this repo.

**Comment by Kiri0824** [comment]
i think i solve this problem
