### ISSUE TITLE
About the .tsv path in yaml

### ISSUE THREAD

**Issue by deegy666** [Audio-WestlakeU/ATST-SED#14]
hello, I would like to ask where should I get each tsv file in yaml? I can't find them in the dataset. Or if you can offer it to me. Thank you very much!

**Comment by SaoYear** [comment]
Hi,

Sorry, I found that I forgot to attach the label files.

I will upload them these days and let you know in this issue once done.

Nian

**Comment by SaoYear** [comment]
The annotations are attached in the xunlei cloud disk link ; )

**Comment by deegy666** [comment]
@SaoYear  Thank you very much！
