### ISSUE TITLE
About Freezing ATST

### ISSUE THREAD

**Issue by bambirogboduq** [Audio-WestlakeU/ATST-SED#17]
Hi @SaoYear , I noticed that in line 112-130 of file [CRNN_e2e.py](https://github.com/Audio-WestlakeU/ATST-SED/blob/main/desed_task/nnet/CRNN_e2e.py), parameter **self.unfreeze_atst_layer** is not working.

So I don't understand how you froze ATST in stage 1, and ATST participated in training in stage 2.

I would be very happy if you could reply as soon as possible. Thank you!

**Comment by SaoYear** [comment]
Hi, sorry for the useless codes and thanks for the interest.

The freezing in applied when defining the optimizer in the `train_stage1.py` and `train_stage2.py`.

It is actually controlled by the `tfm_trainable_layers` in [`stage1.yaml`](https://github.com/Audio-WestlakeU/ATST-SED/blob/main/train/confs/stage1.yaml). Details in line 222 of `train_stage1.py`.

**Comment by bambirogboduq** [comment]
Got it. Thank you !
