### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by visionchan** [Audio-WestlakeU/ATST-SED#18]
In case that the QR code could be expired, if any other developer has problems on the SED implementation, please leave a message in this issue.

_Originally posted by @SaoYear in https://github.com/Audio-WestlakeU/ATST-SED/issues/16#issuecomment-2336625394_
            I am also a beginner of SED. Please rerelease the WeChat Group QR Code. Thanks! I also have a question; when I followed the readme to run the code, I noticed that in the first stage, the code used 8Gb memory of GPU; in the second stage, I must change the batch size of training data to half of all type data, it could work. I tried two chances; the first used about 30Gb memory, and the second used about 25Gb memory (I ran the code in one Tesla V100s GPU 32Gb). I want to know the name, type, and quantity of your process's GPU. Please tell me when I run the second stage code at different times and why it uses different GPU memory. Should I parallel run it ？

**Comment by SaoYear** [comment]
- QR code: ![微信图片_20240923125327](https://github.com/user-attachments/assets/0e6bc501-1b31-41bb-8044-b25e79a2a417)
- About oom warning, please refer to the [repo homepage](https://github.com/Audio-WestlakeU/ATST-SED), Performance, Ablation on batch sizes, where the accumulated gradients is described to face the OOM problem. 

My training device: a single A100-80G; gpu memory in stage 2: > 40G.

For multi-gpu training, I am not sure if its okay to do. You may have to re-construct the dataloader part to meet the multi-gpu request ( I forgot if that's neccessary, please check it by yourself ; ) ) 

Hope it helps,

**Comment by visionchan** [comment]
Thanks (^◡^ )

**Comment by 2502912390** [comment]
你好，请问能重新发一个二维码吗？当前二维码过期了。另外，我想知道如果只有RTX4090是否无法复现您的结果，在stage2我将 batch_size设置为[1,1,2,2]依旧显示out of memory，请问是否有别的方式以支持在（多张）RTX4090上进行训练？
