### ISSUE TITLE
No module named 'sed_scores_eval.utils.scores'

### ISSUE THREAD

**Issue by Osirising** [Audio-WestlakeU/ATST-SED#19]
from . import array_ops
from . import nested
from . import parallel
from . import test
from . import visualization
文件中没有scores这个文件，怎么解决？

**Comment by SaoYear** [comment]
可以直接安装 sed_scores_eval这个库 见 https://github.com/fgnt/sed_scores_eval

**Comment by Osirising** [comment]
Thank you，俺们已经解决嘞个问题嘞。原因是这个库把一些文件挪了一下位置，手动去把引入改一下就ok嘞，谢谢嘞。
