### ISSUE TITLE
Ask help about annotation files!

### ISSUE THREAD

**Issue by Harper812** [Audio-WestlakeU/ATST-SED#2]
Hi, thanks for your opening source. I don't to konw where to get files (strong_val_tsv and strong_val_dur). Would you please send to me via E-mail [hby@bupt.edu.cn](url) or explain how to generate these two files?

**Comment by SaoYear** [comment]
The strong_val_tsv and strong_val_dur files are just the splited validation set from the strong_real set (3000+ clips). It turns out that this real validation set plays a trivial role in the validation. 

So there is no need for you to use them. If you really want to apply them, you can use the attached files.
[audioset_strong_val.zip](https://github.com/Audio-WestlakeU/ATST-SED/files/13200996/audioset_strong_val.zip)

**Comment by Harper812** [comment]
Thank you for replying me instantly! Hope the scientific research goes well！

**Comment by SaoYear** [comment]
An update of the strong real data meta files, including:
strong_real_train.tsv
strong_real_val.tsv
strong_real_val_duration.tsv
[audioset_strong_train_val.zip](https://github.com/Audio-WestlakeU/ATST-SED/files/13213716/audioset_strong_train_val.zip)

**Comment by 2502912390** [comment]
您好，对于strong_val_tsv: "./val_utils/audioset_strong_val.tsv" strong_val_dur: "./val_utils/audioset_strong_val_dur.tsv"
我还是不太理解，您说“there is no need for you to use them.”是指可以直接注释掉代码中读取文件的部分吗？我下载了您发布的数据集， 配置路径如下，
![9337c7c3cf208df2098bff7088967b1](https://github.com/user-attachments/assets/f50850aa-efe0-43e8-b853-9909dc4d0c55)
但是运行的时候会显示有些wav文件不存在，我不知道如何解决，您方便帮我检查一下吗？
 experiment dir: /workspace/ATST-SED/Result/Stage2/Baseline/version_7
Epoch 0:   0%|          | 0/59 [00:00<?, ?it/s] [rank0]: Traceback (most recent call last):
[rank0]:   File "2stage.py", line 500, in <module>
[rank0]:     single_run(
[rank0]:   File "2stage.py", line 356, in single_run
[rank0]:     trainer.fit(desed_training, ckpt_path=checkpoint_resume)
[rank0]:   File "/root/miniconda3/envs/dcase2023/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 538, in fit
[rank0]:     call._call_and_handle_interrupt(
[rank0]:   File "/root/miniconda3/envs/dcase2023/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 46, in _call_and_handle_interrupt
[rank0]:     return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
[rank0]:   File "/root/miniconda3/envs/dcase2023/lib/python3.8/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 105, in launch
[rank0]:     return function(*args, **kwargs)
[rank0]:   File "/root/miniconda3/envs/dcase2023/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 574, in _fit_impl
[rank0]:     self._run(model, ckpt_path=ckpt_path)
[rank0]:   File "/root/miniconda3/envs/dcase2023/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 981, in _run
[rank0]:     results = self._run_stage()
[rank0]:   File "/root/miniconda3/envs/dcase2023/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1025, in _run_stage
[rank0]:     self.fit_loop.run()
[rank0]:   File "/root/miniconda3/envs/dcase2023/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 205, in run
[rank0]:     self.advance()
[rank0]:   File "/root/miniconda3/envs/dcase2023/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 363, in advance
[rank0]:     self.epoch_loop.run(self._data_fetcher)
[rank0]:   File "/root/miniconda3/envs/dcase2023/lib/python3.8/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 140, in run
[rank0]:     self.advance(data_fetcher)
[rank0]:   File "/root/miniconda3/envs/dcase2023/lib/python3.8/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 212, in advance
[rank0]:     batch, _, __ = next(data_fetcher)
[rank0]:   File "/root/miniconda3/envs/dcase2023/lib/python3.8/site-packages/pytorch_lightning/loops/fetchers.py", line 133, in __next__
[rank0]:     batch = super().__next__()
[rank0]:   File "/root/miniconda3/envs/dcase2023/lib/python3.8/site-packages/pytorch_lightning/loops/fetchers.py", line 60, in __next__
[rank0]:     batch = next(self.iterator)
[rank0]:   File "/root/miniconda3/envs/dcase2023/lib/python3.8/site-packages/pytorch_lightning/utilities/combined_loader.py", line 341, in __next__
[rank0]:     out = next(self._iterator)
[rank0]:   File "/root/miniconda3/envs/dcase2023/lib/python3.8/site-packages/pytorch_lightning/utilities/combined_loader.py", line 78, in __next__
[rank0]:     out[i] = next(self.iterators[i])
[rank0]:   File "/root/miniconda3/envs/dcase2023/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
[rank0]:     data = self._next_data()
[rank0]:   File "/root/miniconda3/envs/dcase2023/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1344, in _next_data
[rank0]:     return self._process_data(data)
[rank0]:   File "/root/miniconda3/envs/dcase2023/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1370, in _process_data
[rank0]:     data.reraise()
[rank0]:   File "/root/miniconda3/envs/dcase2023/lib/python3.8/site-packages/torch/_utils.py", line 706, in reraise
[rank0]:     raise exception
[rank0]: RuntimeError: Caught RuntimeError in DataLoader worker process 0.
[rank0]: Original Traceback (most recent call last):
[rank0]:   File "/root/miniconda3/envs/dcase2023/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 309, in _worker_loop
[rank0]:     data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
[rank0]:   File "/root/miniconda3/envs/dcase2023/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
[rank0]:     data = [self.dataset[idx] for idx in possibly_batched_index]
[rank0]:   File "/root/miniconda3/envs/dcase2023/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
[rank0]:     data = [self.dataset[idx] for idx in possibly_batched_index]
[rank0]:   File "/root/miniconda3/envs/dcase2023/lib/python3.8/site-packages/torch/utils/data/dataset.py", line 350, in __getitem__
[rank0]:     return self.datasets[dataset_idx][sample_idx]
[rank0]:   File "/workspace/ATST-SED/desed_task/dataio/datasets_atst_sed.py", line 214, in __getitem__
[rank0]:     mixture, onset_s, offset_s, padded_indx = read_audio(
[rank0]:   File "/workspace/ATST-SED/desed_task/dataio/datasets_atst_sed.py", line 101, in read_audio
[rank0]:     mixture, fs = torchaudio.load(file)
[rank0]:   File "/root/miniconda3/envs/dcase2023/lib/python3.8/site-packages/torchaudio/_backend/utils.py", line 205, in load
[rank0]:     return backend.load(uri, frame_offset, num_frames, normalize, channels_first, format, buffer_size)
[rank0]:   File "/root/miniconda3/envs/dcase2023/lib/python3.8/site-packages/torchaudio/_backend/ffmpeg.py", line 297, in load
[rank0]:     return load_audio(uri, frame_offset, num_frames, normalize, channels_first, format)
[rank0]:   File "/root/miniconda3/envs/dcase2023/lib/python3.8/site-packages/torchaudio/_backend/ffmpeg.py", line 88, in load_audio
[rank0]:     s = torchaudio.io.StreamReader(src, format, None, buffer_size)
[rank0]:   File "/root/miniconda3/envs/dcase2023/lib/python3.8/site-packages/torio/io/_streaming_media_decoder.py", line 526, in __init__
[rank0]:     self._be = ffmpeg_ext.StreamingMediaDecoder(os.path.normpath(src), format, option)
[rank0]: RuntimeError: Failed to open the input "/root/autodl-tmp/DESED/strong_label_real_16k/Y0G78DmKuYlw_300.000_310.000.wav" (No such file or directory).
[rank0]: Exception raised from get_input_format_context at /__w/audio/audio/pytorch/audio/src/libtorio/ffmpeg/stream_reader/stream_reader.cpp:42 (most recent call first):
[rank0]: frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7fb5cbe37f86 in /root/miniconda3/envs/dcase2023/lib/python3.8/site-packages/torch/lib/libc10.so)
[rank0]: frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x7fb5cbde6d10 in /root/miniconda3/envs/dcase2023/lib/python3.8/site-packages/torch/lib/libc10.so)
[rank0]: frame #2: <unknown function> + 0x41ff4 (0x7fb5bf50dff4 in /root/miniconda3/envs/dcase2023/lib/python3.8/site-packages/torio/lib/libtorio_ffmpeg4.so)
[rank0]: frame #3: torio::io::StreamingMediaDecoder::StreamingMediaDecoder(std::string const&, std::optional<std::string> const&, std::optional<std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > > const&) + 0x14 (0x7fb5bf5109f4 in /root/miniconda3/envs/dcase2023/lib/python3.8/site-packages/torio/lib/libtorio_ffmpeg4.so)
[rank0]: frame #4: <unknown function> + 0x3aaee (0x7fb4ecc66aee in /root/miniconda3/envs/dcase2023/lib/python3.8/site-packages/torio/lib/_torio_ffmpeg4.so)
[rank0]: frame #5: <unknown function> + 0x32565 (0x7fb4ecc5e565 in /root/miniconda3/envs/dcase2023/lib/python3.8/site-packages/torio/lib/_torio_ffmpeg4.so)
[rank0]: <omitting python frames>
[rank0]: frame #12: <unknown function> + 0xf65b (0x7fb5c6a9965b in /root/miniconda3/envs/dcase2023/lib/python3.8/site-packages/torchaudio/lib/_torchaudio.so)
