### ISSUE TITLE
yaml配置文件中的数据路径

### ISSUE THREAD

**Issue by WangXD-8** [Audio-WestlakeU/ATST-SED#20]
您好，我想请问一下我下载的数据集总共有6个文件夹，annotation、strong_label_real(3373)、synth_train+val(12500)、unlabel_in_domain_16k(14412)、validation_16k、weak_16k，您的项目配置文件下面有很多个路径，这些是怎么对应的，还是您的数据是重新分过的

**Comment by SaoYear** [comment]
您需要手动分一下synthetic的数据；validation_16k对应development set； 其余可以见下面的说明：

![data_intro](https://github.com/user-attachments/assets/fdb5689c-7809-4f88-9221-5c8d1accbe6c)

folder里是wav的地址（_16k结尾的文件夹）； tsv对应的就是annotation里的文件；

填写时，只用填写16k的地址就行，44k可以不管，因为我都已经处理成16kHz的采样率（44k的地址是如果没有提供16k的地址，代码会自动下采样到16k）。

**Comment by WangXD-8** [comment]
您好，感谢您的分享，我在调用你的预训练模型中遇到了问题，stage1跑不通，您在README文件中说到accm_grad=1这个检查点，请问是怎么操作的
![Uploading 9f2c3f710f5a44cc64138904688712a.png…]()

**Comment by SaoYear** [comment]
诶 我看不到您的图片 是遇到了Out-of-memory问题吗 如果是的话，您可以在stage1.yaml中把 accm_grad 设置成大于1得值，更多可以在这里了解：https://lightning.ai/docs/pytorch/stable/advanced/training_tricks.html

**Comment by SaoYear** [comment]
loading 权重的问题 需要您提供下完整的报错log 以及这大概率和torch的使用有关，可能可以参考下torch的api嘞

**Comment by WangXD-8** [comment]
![9cc11d84e48215e1eefcf6cc733f541](https://github.com/user-attachments/assets/5d4614ea-205d-433b-9e3c-e1a2abd78fed)

**Comment by WangXD-8** [comment]
![9cc11d84e48215e1eefcf6cc733f541](https://github.com/user-attachments/assets/4e0930c8-9494-4d34-a2e8-2fd3647f8872)
