### ISSUE TITLE
关于def load_atst(self, path=None):

### ISSUE THREAD

**Issue by 2502912390** [Audio-WestlakeU/ATST-SED#22]
您好，当前代码里面atst_model.py里面的def load_atst(self, path=None):函数，有两部分关于atst_state_dict的获取，其中第二部分被注释了，请问这两部分有什么区别？我运行inference.py要使用被注释的代码才会运行成功，您能解答一下吗？

**Comment by SaoYear** [comment]
感谢关注工作！

目前未注释部分的代码是用来加载预训练模型(ATSTFrame)。而注释部分代码是用来加载ATST-SED模型的ATST部分参数的。

**Comment by 2502912390** [comment]
十分感谢！！！
