### ISSUE TITLE
关于test_model_state_dict

### ISSUE THREAD

**Issue by 2502912390** [Audio-WestlakeU/ATST-SED#24]
if test_from_checkpoint is not None:
        checkpoint = torch.load(test_from_checkpoint,map_location='cuda:0')
        configs_ckpt = checkpoint["hyper_parameters"]
        configs_ckpt["data"] = configs["data"]
        configs_ckpt["training"]["median_window"] = configs["training"]["median_window"]
        print(
            f"loaded model: {test_from_checkpoint} \n"
            f"at epoch: {checkpoint['epoch']}"
        )
        test_model_state_dict = checkpoint["state_dict"]
        configs = configs_ckpt
好像发现一个小小的bug，在使用您发布的预训练权重进行测试的时候，本地的configs会被此处的configs_ckpt替换掉，如果不设置configs_ckpt["ultra"] = configs["ultra"]，在对模型初始化时，路径会显示您训练时候的路径，导致无法正常进行测试，希望对别人的工作有所帮助。
/home/shaonian/sED2023/DESED_task/recipes/dcase2023_task4_baseline/exp/stage1_new_cnn_stage1_formal/version_0/epoch=199-step=5799.ckpt

**Comment by SaoYear** [comment]
感谢！这是我写的时候未注意到的。你可以做相应更改后提交一个pull request 我来merge到 main branch 里
