### ISSUE TITLE
关于Dcase2023的real strongly labeled dataset

### ISSUE THREAD

**Issue by Yunt1** [Audio-WestlakeU/ATST-SED#25]
您好 非常抱歉打扰了
我正在跑您的代码 同时想跑一下dcase2023的baseline 但是我很难下全它的数据集
我看您的迅雷云盘里面有 其他数据集都是全的
但是real strongly labeled dataset只有3373 我看其他的论文里面这个数据集音频个数应该是3470
请问您有剩下的数据集吗？ 或者只用这个能跑baseline吗

**Comment by SaoYear** [comment]
感谢关注工作，没错 strong数据我这是差了100条 但是不会显著影响性能在 2024年11月15日，11:11，Yunt1 ***@***.***> 写道：﻿
您好 非常抱歉打扰了
我正在跑您的代码 同时想跑一下dcase2023的baseline 但是我很难下全它的数据集
我看您的迅雷云盘里面有 其他数据集都是全的
但是real strongly labeled dataset只有3373 我看其他的论文里面这个数据集音频个数应该是3470
请问您有剩下的数据集吗？ 或者只用这个能跑baseline吗

**Comment by Yunt1** [comment]
好的！非常感谢 可以再问一下 如果使用你们的数据集跑dcase2023 task4 baseline
大概需要修改哪些内容吗？
![e97af26de34ef26732990cae1620a8fe](https://github.com/user-attachments/assets/f0d7e8c4-8010-4f95-85a5-beaf8ef17bc7)

因为文件结构太不一样了 非常感谢！

**Comment by SaoYear** [comment]
我分享的数据就是2023年的baseline数据集，分享的内容与baseline数据区别在于1）100条缺失数据 2）合成数据我直接分享的合成后结果 而不需要手动合成 ：) 
所以只需要在config里将baseline config的数据地址切换为分享的数据地址即可
PS: MAESTRO这个数据集是2024新加入的数据

**Comment by Yunt1** [comment]
谢谢！
