### ISSUE TITLE
the fine-tuned model stage_2_w_external.ckpt is broken

### ISSUE THREAD

**Issue by wanghua-lei** [Audio-WestlakeU/ATST-SED#6]
when I use model stage_2_w_external.ckpt to test the metrics I counter the problem “RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory”. it shows the model is broken. Can you reload it?

**Comment by SaoYear** [comment]
Hi,

Thanks for your interest on our work : )

Yeah, I double checked the uploaded file and it indeed was corrupted.

But unfortunately we lost the exact checkpoint trained by the external dataset. 

I will train a new one and upload it after the holiday. The checkpoint without external dataset is also performance-wisely comparable to the external_ckpt. You could use it for reproduction/development. I would let you know once the new checkpoint was uploaded.

Nian

**Comment by wanghua-lei** [comment]
ok thank you！
